name: agri_connect
description: A Flutter application connecting farmers and consumers for organic produce.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  flutter_svg: ^2.0.5
  shared_preferences: ^2.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  image: ^4.1.3
  path: ^1.8.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  translator: ^1.0.3+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - lib/l10n/
